# Generated by Django 4.2.7 on 2023-12-14 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notepost',
            name='note_update',
        ),
    ]
