# Generated by Django 4.2.7 on 2023-12-19 01:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note', '0005_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='notepost',
            name='likes',
            field=models.ManyToManyField(related_name='notepost_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
